defaults:
  - skip_layer  # Inherit everything from skip_layer.yaml

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model.skip_layer: choice([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]) #[0,1],[0,2],[2,3], [3,4], [4,5], [5,6], [6,7], [7,8], [8,9], [9,10], [10,11], [2,5,8], [3,6,9], [4,7,10], [3,5,7,9], [4,6,8,10], [5,7,9,11], [3,4,5,8,9], [5,6,8,9,11])