defaults:
  - _self_

experiment:
  name: 'skip_layer'
  project: 'skip_layer_gpt2_wikitext'

model:
  name: 'gpt2'
  skip_layer: null  # Set to an integer to skip a specific layer

data:
  block_size: 1024  # Model's max context length
  stride: 512       # Overlap between chunks

trainer:
  gpus: 1
  logger: true
  enable_checkpointing: false


hydra:
  job:
    env_set:
      TOKENIZERS_PARALLELISM: 'false'
